require "rails_helper"

RSpec.describe App::DiffReviewFileClassifier do
  let(:user) { Factories.user(github_token: "ghp_test_token") }
  let(:repo) { Factories.repository(user: user, owner: "acme", name: "widgets", default_branch: "main") }

  subject(:classifier) { described_class.new(repository: repo, user: user) }

  it "marks files generated by repository .syrus.yml generated globs" do
    stub_repository_content(repo, ref: "main", files: {
      ".syrus.yml" => <<~YAML
        generated:
          - command: bin/generate-client
            sources: app/api/schema.graphql
            generates:
              - app/frontend/__generated__/**
      YAML
    })

    match = classifier.classify("app/frontend/__generated__/client.ts")

    expect(match).to have_attributes(
      generated: true,
      generated_reason: "configured generated output",
      generated_source: ".syrus.yml"
    )
  end

  it "marks common generated path patterns without repository configuration" do
    match = classifier.classify("app/models/user.generated.ts")

    expect(match).to have_attributes(
      generated: true,
      generated_reason: "generated file",
      generated_source: "core"
    )
  end

  it "marks lockfiles supplied by dependency audit providers" do
    provider = Class.new do
      def self.lockfiles = [ "custom.lock" ]
    end
    allow(Syrus::PluginRegistry).to receive(:providers_for).and_call_original
    allow(Syrus::PluginRegistry).to receive(:providers_for).with(:dependency_audit_command).and_return([ provider ])
    allow(Syrus::PluginRegistry).to receive(:providers_for).with(:diff_review_file_pattern_provider).and_return([])

    match = classifier.classify("custom.lock")

    expect(match).to have_attributes(
      generated: true,
      generated_reason: "lockfile",
      generated_source: "dependency_audit"
    )
  end
end
