# frozen_string_literal: true

require "open3"
require "fileutils"

module Syrus
  module SurfaceCatalogs
    CATALOGS = {
      user_api: "website/src/content/docs/generated/user-api-catalog.md",
      admin_api: "config/syrus_docs/admin_api_catalog.md",
      mcp: "config/syrus_docs/mcp_tool_catalog.md",
      cli: "website/src/content/docs/generated/cli-catalog.md"
    }.freeze

    def self.render_all(root: Rails.root)
      {
        user_api: render_user_api,
        admin_api: render_admin_api,
        mcp: render_mcp,
        cli: render_cli(root: root)
      }
    end

    def self.write_all!(root: Rails.root)
      render_all(root: root).each do |key, body|
        path = root.join(CATALOGS.fetch(key))
        FileUtils.mkdir_p(path.dirname)
        File.write(path, body)
      end
    end

    def self.committed(root: Rails.root)
      CATALOGS.transform_values do |relative_path|
        path = root.join(relative_path)
        File.exist?(path) ? File.read(path) : nil
      end
    end

    def self.render_user_api
      with_frontmatter(
        title: "User API Catalog",
        description: "Generated endpoint catalog for the Syrus user API.",
        body: render_route_catalog(
          title: "User API catalog",
          intro: "Generated catalog of core `/api/v1/app/*` endpoints, excluding the UI-serving `/api/v1/app/admin/*` namespace. Plugin-owned endpoints belong in the owning plugin's docs.",
          routes: api_routes(prefix: "/api/v1/app", exclude_prefixes: [ "/api/v1/app/admin" ])
        )
      )
    end

    def self.render_admin_api
      render_route_catalog(
        title: "Admin API catalog",
        intro: "Generated catalog of core token-only `/api/v1/admin/*` operator endpoints. Plugin-owned endpoints belong in the owning plugin's docs.",
        routes: api_routes(prefix: "/api/v1/admin")
      )
    end

    def self.render_mcp
      entries = McpToolRegistry.summaries.sort_by { |entry| [ entry[:surface].to_s, entry[:tier].to_s, entry[:tool_name].to_s ] }
      rows = entries.map do |entry|
        [
          "`#{entry.fetch(:tool_name)}`",
          entry.fetch(:surface),
          entry[:tier].presence || "-",
          entry.fetch(:mutation) ? "write" : "read",
          entry.fetch(:admin_only) ? "yes" : "no",
          Array(entry[:required_roles]).presence&.map { |role| "`#{role}`" }&.join(", ") || "-",
          Array(entry[:step_kinds]).presence&.map { |kind| "`#{kind}`" }&.join(", ") || "-",
          entry[:capability].present? ? "`#{entry[:capability]}`" : "-",
          entry[:feature_flag].present? ? "`#{entry[:feature_flag]}`" : "-"
        ]
      end

      <<~MD
        # MCP tool catalog

        <!-- Generated by bin/surface-catalogs. Do not edit by hand. -->

        Generated catalog of MCP tools registered through `McpToolRegistry`.

        | Tool | Surface | Tier | Mode | Admin | Roles | Step kinds | Capability | Feature flag |
        |---|---|---|---|---|---|---|---|---|
        #{rows.map { |row| "| #{row.join(' | ')} |" }.join("\n")}
      MD
    end

    def self.render_cli(root:)
      stdout, stderr, status = Open3.capture3({ "GOWORK" => "off" }, *go_command, "run", "./catalog", chdir: root.join("cli").to_s)
      raise "CLI catalog generation failed:\n#{stderr}" unless status.success?

      with_frontmatter(
        title: "CLI Command Catalog",
        description: "Generated command and flag catalog for the Syrus CLI.",
        body: stdout
      )
    end

    def self.go_command
      return [ "go" ] if system({ "GOWORK" => "off" }, "go", "version", out: File::NULL, err: File::NULL)
      return [ "mise", "exec", "go@1.26.5", "--", "go" ] if system("mise", "--version", out: File::NULL, err: File::NULL)

      [ "go" ]
    end

    def self.api_routes(prefix:, exclude_prefixes: [])
      core_routes(prefix: prefix, exclude_prefixes: exclude_prefixes)
    end

    def self.core_routes(prefix:, exclude_prefixes:)
      Rails.application.routes.routes.filter_map do |route|
        path = route.path.spec.to_s.sub("(.:format)", "")
        next unless path.start_with?(prefix)
        next if exclude_prefixes.any? { |excluded| path.start_with?(excluded) }
        next if path.include?("*plugin_route")

        {
          owner: "core",
          verb: route.verb.to_s,
          path: path,
          controller: "#{route.defaults[:controller]}##{route.defaults[:action]}"
        }
      end
    end

    def self.render_route_catalog(title:, intro:, routes:)
      rows = routes.sort_by { |route| [ route.fetch(:path), route.fetch(:verb), route.fetch(:owner) ] }.map do |route|
        "| #{route.fetch(:owner)} | #{route.fetch(:verb)} | `#{route.fetch(:path)}` | `#{route.fetch(:controller)}` |"
      end

      <<~MD
        # #{title}

        <!-- Generated by bin/surface-catalogs. Do not edit by hand. -->

        #{intro}

        | Owner | Method | Path | Handler |
        |---|---|---|---|
        #{rows.join("\n")}
      MD
    end

    def self.with_frontmatter(title:, description:, body:)
      <<~MD
        ---
        title: #{title}
        description: #{description}
        ---

        #{body}
      MD
    end
  end
end
