module Syrus
  module Metrics
    # Renders the metric catalog: the greppable list that distributed
    # declaration would otherwise cost us.
    #
    # Generated, never hand-maintained -- a hand-written list of metrics drifts
    # within a release, and a catalog nobody trusts is worse than none.
    # spec/docs/metrics_catalog_spec.rb fails the build when the committed file
    # stops matching the registry.
    #
    # **Core metrics only, deliberately.** Enumerating plugin metrics here would
    # put plugin-owned names in a core document, which is exactly what
    # bin/plugin-boundary-audit forbids: deleting a bundled plugin would then
    # change a core file and fail the audit. A plugin's metrics are namespaced
    # `syrus_<plugin>_*` and belong in that plugin's own docs.
    module Catalog
      PATH = "docs/metrics-catalog.md".freeze

      HEADER = <<~MD.freeze
        # Metrics catalog

        <!-- Generated by bin/metrics-catalog. Do not edit by hand. -->

        Every **core** metric Syrus exposes on `/metrics`. Plugin metrics are
        namespaced `syrus_<plugin>_*` and documented by the plugin that owns
        them -- listing them here would make those plugins undeletable.

        `Shared` marks a metric telemetry may send when an operator opts in.
        Nothing is shared unless its declaration says so, and no metric may
        carry an identifying label (see `Syrus::Metrics::TagAllowlist`), so the
        payload structurally cannot contain a repository name, an issue title,
        a prompt or a diff.

        Counters are cumulative and monotonic: they are never reset, and rates
        are computed at read time with `rate()`.

      MD

      def self.render(definitions = Syrus::Metrics.definitions)
        core = definitions.select(&:core?)
        rows = core.map do |definition|
          tags = definition.tags.any? ? definition.tags.map { |t| "`#{t}`" }.join(", ") : "—"
          shared = definition.shared? ? "yes" : "no"
          "| `#{definition.name}` | #{definition.type} | #{tags} | #{shared} | #{definition.comment} |"
        end

        <<~MD
          #{HEADER.rstrip}

          | Metric | Type | Labels | Shared | Description |
          |---|---|---|---|---|
          #{rows.join("\n")}
        MD
      end

      def self.write!(root: Rails.root)
        path = File.join(root, PATH)
        File.write(path, render)
        path
      end

      def self.committed(root: Rails.root)
        path = File.join(root, PATH)
        File.exist?(path) ? File.read(path) : nil
      end
    end
  end
end
