package cmd

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

type CommandCatalogEntry struct {
	Path        string
	Use         string
	Short       string
	Flags       []string
	JSONSupport bool
}

func CommandCatalog(root *cobra.Command) []CommandCatalogEntry {
	var entries []CommandCatalogEntry
	var walk func(prefix string, command *cobra.Command)
	walk = func(prefix string, command *cobra.Command) {
		for _, child := range command.Commands() {
			if child.Hidden {
				continue
			}
			name := strings.Fields(child.Use)
			if len(name) == 0 {
				continue
			}
			path := strings.TrimSpace(prefix + " " + name[0])
			flags := commandFlags(child)
			entries = append(entries, CommandCatalogEntry{
				Path:        path,
				Use:         strings.TrimSpace("syrus " + path + useArgs(child.Use)),
				Short:       child.Short,
				Flags:       flags,
				JSONSupport: hasFlag(flags, "json"),
			})
			walk(path, child)
		}
	}
	walk("", root)
	sort.Slice(entries, func(i, j int) bool { return entries[i].Path < entries[j].Path })
	return entries
}

func RenderCommandCatalog(root *cobra.Command) string {
	var builder strings.Builder
	builder.WriteString("# CLI command catalog\n\n")
	builder.WriteString("<!-- Generated by bin/surface-catalogs. Do not edit by hand. -->\n\n")
	builder.WriteString("Generated catalog of commands registered in the Cobra command tree.\n\n")
	builder.WriteString("| Command | Description | Flags | JSON |\n")
	builder.WriteString("|---|---|---|---|\n")
	for _, entry := range CommandCatalog(root) {
		flags := "-"
		if len(entry.Flags) > 0 {
			quoted := make([]string, 0, len(entry.Flags))
			for _, flag := range entry.Flags {
				quoted = append(quoted, "`--"+flag+"`")
			}
			flags = strings.Join(quoted, ", ")
		}
		json := "no"
		if entry.JSONSupport {
			json = "yes"
		}
		fmt.Fprintf(&builder, "| `%s` | %s | %s | %s |\n", markdownCell(entry.Use), markdownCell(strings.TrimSpace(entry.Short)), flags, json)
	}
	return builder.String()
}

func markdownCell(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}

func commandFlags(command *cobra.Command) []string {
	flagSet := map[string]bool{}
	collect := func(flag *pflag.Flag) {
		if flag.Hidden {
			return
		}
		flagSet[flag.Name] = true
	}
	command.LocalFlags().VisitAll(collect)
	command.InheritedFlags().VisitAll(collect)

	flags := make([]string, 0, len(flagSet))
	for flag := range flagSet {
		flags = append(flags, flag)
	}
	sort.Strings(flags)
	return flags
}

func hasFlag(flags []string, name string) bool {
	for _, flag := range flags {
		if flag == name {
			return true
		}
	}
	return false
}

func useArgs(use string) string {
	parts := strings.Fields(use)
	if len(parts) <= 1 {
		return ""
	}
	return " " + strings.Join(parts[1:], " ")
}
